services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_container
    image: mariadb:42
    networks:
      - inception_net
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    env_file:
      - .env

  nginx:
    build: 
      context: ./requirements/nginx
      args:
        CERT_PATH: $CERT_PATH
        PRIVKEY_PATH: $PRIVKEY_PATH
        CERT_DETAILS: $CERT_DETAILS
      # Dockerfileでコンテナビルド時に使う環境変数を用意
    container_name: nginx_container
    image: nginx:42
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - 443:443

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress_container
    image: wordpress:42
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb

networks:
  inception_net:
    name: inception_network

volumes:
  mariadb_vol:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: bind
      device: ${MARIADB_VOLUME_PATH}
      o: bind

  wordpress_vol:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_VOLUME_PATH}
      o: bind
